resources:
  pipelines:
    lakehouse:
      name: a2b_airline_ops_lakehouse_${var.env}
      catalog: ${var.catalog}
      schema: ${var.env}_lakehouse
      serverless: true

      libraries:
        - file:
            path: ../src/pipeline/bronze.py
        - file:
            path: ../src/pipeline/silver.py
        - file:
            path: ../src/pipeline/gold.sql

      configuration:
        a2.landing: /Volumes/${var.catalog}/${var.env}_landing/raw
        a2.lakehouse: ${var.catalog}.${var.env}_lakehouse
        a2.gold: ${var.catalog}.${var.env}_gold
        a2.ops: ${var.catalog}.${var.env}_ops